name: Develop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test
      run: |
        rustup target add riscv64imac-unknown-none-elf
        cargo build --examples
